name: CI

on: [push, pull_request]

jobs:
  rubies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ ruby-head, '3.0', '2.7' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          rm Gemfile.lock
          bundle install
      - name: Run test
        run: bundle exec rake
      - name: Install gem
        run: bundle exec rake install
